version: '3.1'

services:
  # db:
  #   image: postgres:9.4
  #   environment:
  #     POSTGRES_USER: pguser
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: myapp
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./dump:/docker-entrypoint-initdb.d

  frontend:
    tty: true
    stdin_open: true
    build: ./docker/frontend
    # links:
    #   - backend
    volumes:
      - ./frontend:/app:cached
    command: ["yarn", "dev"]
    networks:
      - app_network

  nginx:
    depends_on:
      - frontend
    image: nginx:alpine
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  # backend:
  #   tty: true
  #   stdin_open: true
  #   command: sh ./docker/app/docker-entrypoint.sh
  #   build: ./docker/backend
  #   links:
  #     - db
  #   volumes:
  #     - ./backend:/app:cached
  #     - bundle_cache:/app/vendor/bundle

# volumes:
#   bundle_cache:
networks:
  app_network:
    driver: bridge
